parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shared\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../DomainModel/Model/'
            - '../../Tests/'
            - '../../**/Tests/'
        tags: ['controller.service_arguments']

    # Global Assert Validation Error Handler
    Shared\Infrastructure\ErrorHandler\GlobalErrorHandler:
        tags:
            - { name: kernel.event_subscriber }

    # Responder
    Shared\Presentation\Responder\JsonResponder:
        tags:
            - { name: kernel.event_subscriber }

    Shared\Presentation\Responder\HtmlResponder:
        tags:
            - { name: kernel.event_subscriber }
