parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shared\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Presentation/Api/{Request,Response}/'
            - '../../Presentation/Web/{Request,Response}/'
            - '../../Presentation/Console/{Input,Output}/'
            - '../../Application/**/*Command.php'
            - '../../Application/**/*Query.php'
            - '../../Application/{Exception}/'
            - '../../Infrastructure/Outbox/Command/OutboxMessageEnvelope.php'
            - '../../Infrastructure/RateLimiting/{Configuration,Exception,Attribute,Dto}/'
            - '../../Infrastructure/RateLimiting/RateLimiter.php'
            - '../../Infrastructure/Outbox/{ValueObject}/'
            - '../../DomainModel/{Dto,Event,Enum,Entity,Specification,Exception,ValueObject}/'
            - '../../**/Tests/'
        tags: ['controller.service_arguments']

    query.bus.adapter:
        class: Shared\Infrastructure\MessageBus\SymfonyMessageBus
        arguments:
            $messageBus: '@query.bus'

    event.bus.adapter:
        class: Shared\Infrastructure\MessageBus\SymfonyMessageBus
        arguments:
            $messageBus: '@event.bus'

    command.bus.adapter:
        class: Shared\Infrastructure\MessageBus\SymfonyMessageBus
        arguments:
            $messageBus: '@command.bus'

    Shared\Infrastructure\TransactionDoctrineTransactionService:
        arguments:
            - '%doctrine.orm.default_entity_manager%'

    OrderContext\Infrastructure\Transaction\TransactionServiceInterface:
        alias: Shared\Infrastructure\TransactionDoctrineTransactionService

    # Global Assert Validation Error Handler
    Shared\Infrastructure\ErrorHandler\GlobalErrorHandler:
        tags:
            - { name: kernel.event_subscriber }

    # Responder
    Shared\Presentation\Responder\JsonResponder:
        tags:
            - { name: kernel.event_subscriber }

    Shared\Presentation\Responder\HtmlResponder:
        tags:
            - { name: kernel.event_subscriber }

    # Outbox
    Shared\Infrastructure\Outbox\Repository\OutboxEventRepository:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    Shared\Infrastructure\Outbox\Service\OutboxEventProcessor:
        arguments:
            $eventBus: '@event.bus.adapter'

    Shared\Infrastructure\Outbox\Command\OutboxMessageEnvelopeHandler:
        arguments:
            $eventBus: '@event.bus.adapter'
        tags:
            - { name: 'messenger.message_handler', bus: 'event.bus' }

    #############################################################################
    # Event Store
    #############################################################################
    Shared\Infrastructure\EventStore\Repository\DoctrineEventStore:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    Shared\Infrastructure\EventStore\EventStoreInterface:
        class: Shared\Infrastructure\EventStore\Repository\DoctrineEventStore

    # Services
    OrderContext\Application\Service\ApplicationService: ~