framework:
    messenger:
        routing:
            # events
            OrderContext\DomainModel\Event\OrderStatusChangedEvent: sync
            # commands
            PaymentContext\Application\UseCases\UpdateInventory\Command\UpdateInventoryCommand: sync
