parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    PaymentContext\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Presentation/Api/{Request,Response}/'
            - '../../Presentation/Web/{Request,Response}/'
            - '../../Presentation/Console/{Input,Output}/'
            - '../../Application/**/*Command.php'
            - '../../Application/**/*Query.php'
            - '../../Application/**/*Dto.php'
            - '../../Application/**/*Exception.php'
            - '../../DomainModel/{Dto,Event,Enum,Entity,Exception,ValueObject}/'
            - '../../**/Tests/'
        tags: [ 'controller.service_arguments' ]
        
    PaymentContext\Application\EventHandler\OrderStatusChangedEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'event.bus' }

    PaymentContext\Application\UseCases\UpdateInventory\Command\UpdateInventoryCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'command.bus' }