parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\OrderContext\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../DomainModel/Model/'
            - '../../Tests/'
            - '../../**/Tests/'
        tags: ['controller.service_arguments']