framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        # Defining message buses (CQRS)
        default_bus: command.bus
        buses:
            event.bus:
                default_middleware: allow_no_handlers
            command.bus: ~
            query.bus: ~
            messenger.bus.default: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # failed: 'doctrine://default?queue_name=failed'
             sync: 'sync://'
#            async: '%env(MESSENGER_TRANSPORT_DSN)%'
#            sync: 'in-memory://default'

        routing:

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
