<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Миграция для создания таблицы order_items
 */
final class Version20250604134522 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create order_items table for Order aggregate';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE order_items (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            order_id UUID NOT NULL, 
            product_id VARCHAR NOT NULL, 
            quantity INT NOT NULL, 
            price NUMERIC(10,2) NOT NULL,
            currency VARCHAR(3) NOT NULL,
            PRIMARY KEY(id)
        )');
        
        $this->addSql('CREATE INDEX IDX_62809DB08D9F6D38 ON order_items (order_id)');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB08D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE order_items DROP CONSTRAINT FK_62809DB08D9F6D38');
        $this->addSql('DROP TABLE order_items');
    }
}
